### PR TITLE
Make trivial instances explicit

### PR DESCRIPTION
**Pull request by maximedenes**
This is in preparation for https://github.com/coq/coq/pull/9274.

Should be backward-compatible, but that remains to be tested.

### CODE REVIEW

**Comment by Zimmi48** [comment]
I started a build in the master branch and it failed in the same way: https://travis-ci.org/coq-community/math-classes/builds/483950733

**Comment by Zimmi48** [comment]
Unless someone understands the problem before, I can try to work on math-classes and corn CI tomorrow.

**Comment by maximedenes** [comment]
> Unless someone understands the problem before, I can try to work on math-classes and corn CI tomorrow.

Any progress in understanding the issue?

**Comment by Zimmi48** [comment]
FTR, I was not really saying that I would try to understand the issue. What I have in mind instead is to move math-classes and corn to one of the two standard CI solutions in use in the rest of the coq-community projects.

**Comment by maximedenes** [comment]
Oh sure, as long as I can get this PR merged, I'm fine :)

**Comment by Zimmi48** [comment]
FTR I have a [branch](https://github.com/Zimmi48/math-classes/tree/meta-file-ci-etc) doing this but it doesn't work yet: https://travis-ci.com/Zimmi48/math-classes/builds/98644946
The test with Nix and Coq master doesn't work because it can't find the right version of bignums. @vbgl: I don't remember if we had a solution to this (for now it says `error: attribute '8.10-git' missing, at /nix/store/7v01szrjw921m8zzqlzf6a95j5ibm7p6-nixpkgs-19.03pre167327.11cf7d6e1ff/nixpkgs/pkgs/development/coq-modules/bignums/default.nix:21:11`).
The test with opam and coq.dev fails in a way that is more frightening:
```
# File "./theory/products.v", line 11, characters 2-40:
# Error: Unsolved obligations remaining.
```

**Comment by vbgl** [comment]
You need to override `bignums`, as in:

~~~
let bignums = coqPackages.bignums.overrideAttrs (o: {
  src = fetchTarball https://github.com/coq/bignums/archive/master.tar.gz;
}); in
~~~

(not tested)

**Comment by Zimmi48** [comment]
Thanks @vbgl. We need to think of the right way to handle this in all generality...
FTR the error I saw in the opam build was just because my branch was not up-to-date.
I'm opening a PR with my CI updates. I will try to take care of corn later in the day.

**Comment by Zimmi48** [comment]
CI passed. I'll merge this.

**Comment by maximedenes** [comment]
Thanks, there's also the sister PR: https://github.com/coq-community/corn/pull/65

**Pull request merged**
